name: past present
favicon: null
layout_spectrum: 0.5364950727671385
typography_spectrum: 0.3620053406339139
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9666704703122377
  lightness: 0.8708174047060311
  saturation: 0.4679705735761672
  rhythmicContrast: 0.21272068424150348
purpose: []
